In [1]:
import numpy as np
X = np.array([[4,10],[5,15]]).transpose()
X

array([[ 4,  5],
       [10, 15]])

In [6]:
y = np.array([3, 6])

In [14]:
y = np.append(y, 4)

In [15]:
y

array([3, 6, 4])

In [27]:
a = np.array([1,1,1,1])

In [31]:
a = []

1.0

In [3]:
means, stds = (X.mean(axis = 0), X.std(axis = 1))
print means, stds

[  7.  10.] [ 0.5  2.5]


In [4]:
X.drop(axis = )

AttributeError: 'numpy.ndarray' object has no attribute 'drop'

numpy.ndarray

In [69]:
X = (np.array([X[:,0]/means[0], X[:,1]/means[1]])).transpose()
X

array([[ 0.57142857,  0.5       ],
       [ 1.42857143,  1.5       ]])

In [102]:
a = [10,5]

In [111]:
np.ones((len(X[:,0]), 1))

array([[ 1.],
       [ 1.]])

In [113]:

A = np.hstack((np.ones((len(X[:,0]), 1)), X))
A

array([[  1.,   4.,   5.],
       [  1.,  10.,  15.]])

In [120]:
Y = np.array([4,6])
C = np.array([1,2])
np.linalg.norm(Y-C)

5.0

In [125]:
F = np.array([4]*4)
F

array([4, 4, 4, 4])

In [129]:
[F.mean()]*len(F)

[4.0, 4.0, 4.0, 4.0]

In [139]:
x1 = np.array([[1, 1], [2, 1]])
x2 = np.array([[-1, 1], [2, -1]])

In [141]:
x2.dot(x1)

array([[1, 0],
       [0, 1]])

In [143]:
np.array([0,0,0])

array([0, 0, 0])